# Лабораторная работа №2

In [5]:
!pwd

/Users/artyem.petrov/dev/university/4-1/machine-learning-basics-and-neural-networks/lab02


In [6]:
!../.venv/bin/pip install numpy

  Using cached numpy-2.3.5-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.3.5-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: /Users/artyem.petrov/dev/university/4-1/machine-learning-basics-and-neural-networks/.venv/bin/python -m pip install --upgrade pip


In [7]:
import numpy as np

# Задача 2.1

Создайте одномерный массив чисел от 0 до 8.

Сделайте это двумя способами: с помощью метода `arange` из numpy и с помощью преобразования списка (list) в numpy array

In [8]:
def create_array_arange():
    return np.arange(9)

def create_array_from_list():
    return np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
def run_tests():
    expected = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
    
    print("Запуск тестов:\n")
    all_passed = True
    
    result1 = create_array_arange()
    status1 = "ПРОЙДЕН" if np.array_equal(result1, expected) else "НЕ ПРОЙДЕН"
    print(f"Тест 1 (arange): {status1}")
    print(f"  Ожидалось: {expected}")
    print(f"  Получено:  {result1}")
    if not np.array_equal(result1, expected):
        all_passed = False
    print()
    
    result2 = create_array_from_list()
    status2 = "ПРОЙДЕН" if np.array_equal(result2, expected) else "НЕ ПРОЙДЕН"
    print(f"Тест 2 (from list): {status2}")
    print(f"  Ожидалось: {expected}")
    print(f"  Получено:  {result2}")
    if not np.array_equal(result2, expected):
        all_passed = False
    print()
    
    print("=" * 50)
    if all_passed:
        print("Все тесты пройдены успешно!")
    else:
        print("Некоторые тесты не пройдены!")
    
    return all_passed

In [9]:
run_tests()

Запуск тестов:

Тест 1 (arange): ПРОЙДЕН
  Ожидалось: [0 1 2 3 4 5 6 7 8]
  Получено:  [0 1 2 3 4 5 6 7 8]

Тест 2 (from list): ПРОЙДЕН
  Ожидалось: [0 1 2 3 4 5 6 7 8]
  Получено:  [0 1 2 3 4 5 6 7 8]

Все тесты пройдены успешно!


True

## Задача 2.2

Вам дан numpy array под названием test_array. Выведите положительные элементы этого массива

Подсказка: здесь можно также использовать булевы массивы в качестве булевой маски.

In [10]:
def get_positive_elements(arr):
    return arr[arr > 0]

In [12]:
def run_tests():
    test_cases = [
        (np.array([0, -1, 5, -3, 7, -1, 6, -1, 8, -1]), np.array([5, 7, 6, 8]))
    ]
    
    print("Запуск тестов:\n")
    all_passed = True
    
    for i, (test_array, expected) in enumerate(test_cases, 1):
        result = get_positive_elements(test_array)
        status = "ПРОЙДЕН" if np.array_equal(result, expected) else "НЕ ПРОЙДЕН"
        
        print(f"Тест {i}: {status}")
        print(f"  Вход: {test_array}")
        print(f"  Ожидалось: {expected}")
        print(f"  Получено:  {result}")
        
        if not np.array_equal(result, expected):
            all_passed = False
        print()
    
    print("=" * 50)
    if all_passed:
        print("Все тесты пройдены успешно!")
    else:
        print("Некоторые тесты не пройдены!")
    
    return all_passed

In [13]:
run_tests()

Запуск тестов:

Тест 1: ПРОЙДЕН
  Вход: [ 0 -1  5 -3  7 -1  6 -1  8 -1]
  Ожидалось: [5 7 6 8]
  Получено:  [5 7 6 8]

Все тесты пройдены успешно!


True

## Задача 2.3

Замените отрицательные элементы из массива test_array на 0. Подсказка: вам пригодится функция np.where

In [14]:
def replace_negatives_with_zero(arr):
    return np.where(arr < 0, 0, arr)

In [16]:
def run_tests():
    test_cases = [
        (np.array([0, -1, 5, -3, 7, -1, 6, -1, 8, -1]), np.array([0, 0, 5, 0, 7, 0, 6, 0, 8, 0]))
    ]
    
    print("Запуск тестов:\n")
    all_passed = True
    
    for i, (test_array, expected) in enumerate(test_cases, 1):
        result = replace_negatives_with_zero(test_array)
        status = "ПРОЙДЕН" if np.array_equal(result, expected) else "НЕ ПРОЙДЕН"
        
        print(f"Тест {i}: {status}")
        print(f"  Вход: {test_array}")
        print(f"  Ожидалось: {expected}")
        print(f"  Получено:  {result}")
        
        if not np.array_equal(result, expected):
            all_passed = False
        print()
    
    print("=" * 50)
    if all_passed:
        print("Все тесты пройдены успешно!")
    else:
        print("Некоторые тесты не пройдены!")
    
    return all_passed

In [17]:
run_tests()

Запуск тестов:

Тест 1: ПРОЙДЕН
  Вход: [ 0 -1  5 -3  7 -1  6 -1  8 -1]
  Ожидалось: [0 0 5 0 7 0 6 0 8 0]
  Получено:  [0 0 5 0 7 0 6 0 8 0]

Все тесты пройдены успешно!


True

## Задача 2.4

Вам дан массив из 10 чисел. С помощью одной функции в numpy найдите позицию максимального элемента в заданном массиве

In [18]:
def find_max_position(arr):
    return np.argmax(arr)

In [19]:
def run_tests():
    test_cases = [
        (np.array([6, 8, 4, 2, 11, -3, 7, 22, -20, -30]), 7)
    ]
    
    print("Запуск тестов:\n")
    all_passed = True
    
    for i, (test_array, expected) in enumerate(test_cases, 1):
        result = find_max_position(test_array)
        status = "ПРОЙДЕН" if result == expected else "НЕ ПРОЙДЕН"
        
        print(f"Тест {i}: {status}")
        print(f"  Вход: {test_array}")
        print(f"  Ожидалось: {expected}")
        print(f"  Получено:  {result}")
        
        if result != expected:
            all_passed = False
        print()
    
    print("=" * 50)
    if all_passed:
        print("Все тесты пройдены успешно!")
    else:
        print("Некоторые тесты не пройдены!")
    
    return all_passed

In [20]:
run_tests()

Запуск тестов:

Тест 1: ПРОЙДЕН
  Вход: [  6   8   4   2  11  -3   7  22 -20 -30]
  Ожидалось: 7
  Получено:  7

Все тесты пройдены успешно!


True

## Задача 2.5

Вам дан словарь, в котором подсчитаны частоты женских имен в выборке из 26 новорожденных девочек.

In [24]:
from typing import Dict

names = {
    'Катя': 8,
    'Маша': 5,
    'Вероника': 2,
    'Ярослава': 1,
    'Александра': 10
}

In [25]:
def calculate_name_percentages(names_dict: Dict[str, int]) -> int:
    values = np.array(list(names_dict.values()))
    total = np.sum(values)
    return values / total

In [26]:
def run_tests():
    expected = np.array([0.30769231, 0.19230769, 0.07692308, 0.03846154, 0.38461538])
    
    print("Запуск тестов:\n")
    all_passed = True
    
    result = calculate_name_percentages(names)
    status = "ПРОЙДЕН" if np.allclose(result, expected) else "НЕ ПРОЙДЕН"
    
    print(f"Тест 1: {status}")
    print(f"  Вход: {names}")
    print(f"  Ожидалось: {expected}")
    print(f"  Получено:  {result}")
    
    if not np.allclose(result, expected):
        all_passed = False
    print()
    
    print("=" * 50)
    if all_passed:
        print("Все тесты пройдены успешно!")
    else:
        print("Некоторые тесты не пройдены!")
    
    return all_passed

In [27]:
run_tests()

Запуск тестов:

Тест 1: ПРОЙДЕН
  Вход: {'Катя': 8, 'Маша': 5, 'Вероника': 2, 'Ярослава': 1, 'Александра': 10}
  Ожидалось: [0.30769231 0.19230769 0.07692308 0.03846154 0.38461538]
  Получено:  [0.30769231 0.19230769 0.07692308 0.03846154 0.38461538]

Все тесты пройдены успешно!


True

## Задача 2.6

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 5, и строго меньше 9

Подсказка: здесь можно использовать булевы массивы в качестве булевой маски.

In [28]:
def filter_elements(arr):
    return arr[(arr > 5) & (arr < 9)]

In [29]:
def run_tests():
    test_cases = [
        (np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8]), np.array([7, 7, 8]))
    ]
    
    print("Запуск тестов:\n")
    all_passed = True
    
    for i, (test_array, expected) in enumerate(test_cases, 1):
        result = filter_elements(test_array)
        status = "ПРОЙДЕН" if np.array_equal(result, expected) else "НЕ ПРОЙДЕН"
        
        print(f"Тест {i}: {status}")
        print(f"  Вход: {test_array}")
        print(f"  Ожидалось: {expected}")
        print(f"  Получено:  {result}")
        
        if not np.array_equal(result, expected):
            all_passed = False
        print()
    
    print("=" * 50)
    if all_passed:
        print("Все тесты пройдены успешно!")
    else:
        print("Некоторые тесты не пройдены!")
    
    return all_passed

In [30]:
run_tests()

Запуск тестов:

Тест 1: ПРОЙДЕН
  Вход: [ 7  2 10  2  7  4  9  4  9  8]
  Ожидалось: [7 7 8]
  Получено:  [7 7 8]

Все тесты пройдены успешно!


True

## Задача 2.7

Создайте методом из numpy одномерный массив из 12 элементов от 0 до 11 и сделайте из него матрицу размером 3х4 (вам пригодится функция np.reshape)

In [34]:
def create_reshaped_matrix():
    arr = np.arange(12)
    return arr.reshape(3, 4)

In [35]:
mtr = create_reshaped_matrix()

mtr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Задача 2.8

Соедините вертикально и горизонтально две созданные матрицы a и b.

In [36]:
def concatenate_matrices(a, b):
    vertical = np.vstack((a, b))
    horizontal = np.hstack((a, b))
    return vertical, horizontal

In [37]:
a = np.arange(8).reshape(2,4)
b = np.ones(8).reshape(2,4)

In [44]:
vstacked, hstacked = concatenate_matrices(a, b)

print(f'Вертикально соединенные матрицы размерностей a.shape={a.shape} и b.shape={b.shape}:\n{vstacked}')
print(f'Горизонтально соединенные матрицы размерностей a.shape={a.shape} и b.shape={b.shape}:\n{hstacked}')

Вертикально соединенные матрицы размерностей a.shape=(2, 4) и b.shape=(2, 4):
[[0. 1. 2. 3.]
 [4. 5. 6. 7.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Горизонтально соединенные матрицы размерностей a.shape=(2, 4) и b.shape=(2, 4):
[[0. 1. 2. 3. 1. 1. 1. 1.]
 [4. 5. 6. 7. 1. 1. 1. 1.]]


## Задача 2.9

Сохраните в отдельную переменную второй столбец (столбец с индексом 1) из данного вам двумерного массива.

Обратите внимение, что при вырезании столбца из матрицы, у вас получится одномерный numpy-array, а не двумерная матрица с одним столбцом!

In [46]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
def get_second_column(matrix):
    return matrix[:, 1]

In [48]:
res = get_second_column(arr)

res

array([1, 5, 9])

## Задача 2.10

Создайте массив из случайных чисел размера 3 на 4 (3 строки и 4 столбца) и сохраните его в переменную random_array. Найдите среднее, медиану, стандартное отклонение созданной матрицы random_array по строкам и по столбцам. По одной строке на среднее, медиану, и стандартное отклонение для операций по строкам и по столбцам - всего должно получиться 6 строк кода. Результатом каждой из этих операций должен быть вектор. Какова длина вектора в каждом из этих случаев?

In [49]:
def analyze_random_array():
    np.random.seed(42)
    random_array = np.random.rand(3, 4)
    
    mean_rows = np.mean(random_array, axis=1)
    mean_cols = np.mean(random_array, axis=0)
    median_rows = np.median(random_array, axis=1)
    median_cols = np.median(random_array, axis=0)
    std_rows = np.std(random_array, axis=1)
    std_cols = np.std(random_array, axis=0)
    
    return random_array, mean_rows, mean_cols, median_rows, median_cols, std_rows, std_cols

In [53]:
random_array, mean_rows, mean_cols, median_rows, median_cols, std_rows, std_cols = analyze_random_array()

print(f"Исходный массив:\n{random_array}\n")
print(f"Среднее по строкам: {mean_rows} (длина: {len(mean_rows)})")
print(f"Среднее по столбцам: {mean_cols} (длина: {len(mean_cols)})")
print(f"Медиана по строкам: {median_rows} (длина: {len(median_rows)})")
print(f"Медиана по столбцам: {median_cols} (длина: {len(median_cols)})")
print(f"Стандартное отклонение по строкам: {std_rows} (длина: {len(std_rows)})")
print(f"Стандартное отклонение по столбцам: {std_cols} (длина: {len(std_cols)})")

Исходный массив:
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

Среднее по строкам: [0.66397671 0.30906823 0.57492048] (длина: 3)
Среднее по столбцам: [0.37722459 0.60492713 0.27022068 0.81158149] (длина: 4)
Медиана по строкам: [0.66532621 0.15600658 0.65459379] (длина: 3)
Медиана по столбцам: [0.37454012 0.70807258 0.05808361 0.86617615] (длина: 4)
Стандартное отклонение по строкам: [0.20909615 0.32412121 0.34703048] (длина: 3)
Стандартное отклонение по столбцам: [0.18171975 0.33253984 0.32688168 0.15640189] (длина: 4)


## Задача 2.11

Еще раз найдите только средние значения по строкам у созданной в задании 2.10 матрицы random_array (одна строка кода). Вычтите полученные средние значения из соответствующих строк исходной матрицы random_array. Проверьте, что после вычитания средних среднее по каждой строке стало равно 0. Результат - вектор.

In [54]:
def center_rows():
    np.random.seed(42)
    random_array = np.random.rand(3, 4)
    
    mean_rows = np.mean(random_array, axis=1, keepdims=True)
    centered_array = random_array - mean_rows
    new_means = np.mean(centered_array, axis=1)
    
    return random_array, centered_array, new_means

In [56]:
random_array, centered_array, new_means = center_rows()
    
print(f"Исходный массив:\n{random_array}\n")
print(f"Массив после центрирования:\n{centered_array}\n")
print(f"Новые средние по строкам: {new_means}")

is_zero = np.allclose(new_means, 0)
print(f"\nСредние равны нулю: {is_zero}")

Исходный массив:
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

Массив после центрирования:
[[-0.28943659  0.28673759  0.06801723 -0.06531823]
 [-0.15304959 -0.15307371 -0.25098462  0.55710792]
 [ 0.02619453  0.13315209 -0.55433599  0.39498937]]

Новые средние по строкам: [-2.77555756e-17  0.00000000e+00  0.00000000e+00]

Средние равны нулю: True


## Задача 2.12

Пусть мы имеем 2 массива (заданы ниже). Требуется создать массив, который получает результат поэлементно:

True, если элементы 1-го массива с четными индексами больше соответствующих элементов 2-го массива и

True, если элементы 2-го массива с нечетными индексами больше соответствующих элементов 1-го массива.

В противном случае возвращать False.

Реализовать задачу с помощью numpy

Пример массивов и результата:

a = [7, 3, 5, 9, 2, 5, 4, 8, 9, 0]

b = [2, 8, 6, 7, 1, 3, 2, 9, 5, 1]

res = [ True, True, False, False, True, False, True, True, True, True]

Вы можете сделать задачу с помощью слайсинга или комбинации функций np.arange и np.where

In [57]:
def compare_arrays(a, b):
    a = np.array(a)
    b = np.array(b)
    res = np.zeros(len(a), dtype=bool)
    
    even_indices = np.arange(0, len(a), 2)
    odd_indices = np.arange(1, len(a), 2)
    
    res[even_indices] = a[even_indices] > b[even_indices]
    res[odd_indices] = b[odd_indices] > a[odd_indices]
    
    return res

In [60]:
a = [7, 3, 5, 9, 2, 5, 4, 8, 9, 0]
b = [2, 8, 6, 7, 1, 3, 2, 9, 5, 1]
print(compare_arrays(a, b))

[ True  True False False  True False  True  True  True  True]


## Задача 2.13

Создайте массив размера 10 со значениями от 0 до 1 (интервал между значениями равномерный), не включая концы. См np.linspace + слайсинг

In [61]:
def create_uniform_array():
    return np.linspace(0, 1, 12)[1:-1]

In [67]:
expected = np.array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])
result = create_uniform_array()

print(f"Ожидалось:\n{expected}")
print(f"Получили:\n{result}")
print(f"Равны ли: {np.allclose(result, expected)}")

Ожидалось:
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
Получили:
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
Равны ли: True


## Задача 2.14

Создайте случайный вектор размера 10, и замените в нем максимальное значение на 0

In [68]:
def replace_max_with_zero():
    np.random.seed(42)
    vector = np.random.rand(10)
    vector[np.argmax(vector)] = 0
    return vector

In [70]:
result = replace_max_with_zero()
print(result)

[0.37454012 0.         0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
